import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Heart = localFont({
  src: "./fonts/Heart.ttf",
  variable: "--font-heart",
  weight: "100 900",
});
const Motter = localFont({
  src: "./fonts/Motter.otf",
  variable: "--font-motter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Motter.variable} ${Heart.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
